### ISSUE TITLE
ImportError: cannot import name GUdev, introspection typelib not found

### ISSUE THREAD

**Issue by kareemaly** [henrywoo/kazam#16]
Dear Maintainers, I'm getting this error on `Ubuntu 22.04.02 LTS`
```bash
$ kazam --debug

WARNING Kazam - Failed to correctly detect operating system.
DEBUG Kazam - Starting ...
DEBUG Kazam - Running on: Ubuntu 12.10
DEBUG Kazam - Kazam version: 1.5.6 Bulldog
DEBUG Kazam - Starting new instance ...
Traceback (most recent call last):
  File "/home/kareem/.local/bin/kazam", line 148, in <module>
    from kazam.app import KazamApp
  File "/home/kareem/.local/lib/python3.10/site-packages/kazam/app.py", line 36, in <module>
    from kazam.backend.prefs import *
  File "/home/kareem/.local/lib/python3.10/site-packages/kazam/backend/prefs.py", line 30, in <module>
    from kazam.backend.webcam import Webcam
  File "/home/kareem/.local/lib/python3.10/site-packages/kazam/backend/webcam.py", line 24, in <module>
    from gi.repository import GObject, GUdev
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 136, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GUdev, introspection typelib not found
```

**Comment by DemonRx** [comment]
Install the package `gir1.2-gudev-1.0`

**Comment by henrywoo** [comment]
And please try the latest version:

`pip install kazam -U`

This should fix your issue.
