### ISSUE TITLE
GstVideo not available

### ISSUE THREAD

**Issue by MissingTwins** [henrywoo/kazam#36]
```
~$ uname -a
Linux ben-NucBox7 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

~$ sudo apt install build-essential libpython3-dev \
libdbus-1-dev libcairo2-dev libgirepository1.0-dev \
gir1.2-gudev-1.0 gir1.2-keybinder-3.0 -y

~$ pip install kazam

~$ kazam
/home/user/.local/lib/python3.10/site-packages/kazam/backend/prefs.py:428: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
INFO Webcam - Webcam not detected.
INFO Webcam - Webcam not detected.
Traceback (most recent call last):
  File "/home/user/.local/bin/kazam", line 149, in <module>
    from kazam.app import KazamApp
  File "/home/user/.local/lib/python3.10/site-packages/kazam/app.py", line 39, in <module>
    from kazam.backend.gstreamer import Screencast, GWebcam
  File "/home/user/.local/lib/python3.10/site-packages/kazam/backend/gstreamer.py", line 37, in <module>
    gi.require_version('GstVideo', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GstVideo not available
```
**solved `GstVideo not available` by refering t**o https://github.com/henrywoo/kazam/issues/19#issuecomment-1527039908  
```
~$ sudo apt install gir1.2-gst-plugins-bad-1.0 gir1.2-gst-plugins-base-1.0

~$ kazam
INFO Webcam - Webcam not detected.
INFO Webcam - Webcam not detected.
/home/user/.local/lib/python3.10/site-packages/kazam/frontend/indicator.py:152: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

(kazam:10972): Gtk-WARNING **: 03:19:39.901: Can't set a parent on widget which has a parent

(kazam:10972): Gtk-WARNING **: 03:19:39.903: Can't set a parent on widget which has a parent
```

**Icons are missing**
![image](https://github.com/henrywoo/kazam/assets/146804746/0a979e87-c204-4642-80af-8b9ad9b9dab6)

**The File->Preferences can only be opened for once, the 2nd time causing the following error**
```
(kazam:11531): Gtk-WARNING **: 03:32:41.851: Can't set a parent on widget which has a parent
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/kazam/app.py", line 654, in cb_preferences_request
    self.preferences_window = Preferences()
  File "/home/user/.local/lib/python3.10/site-packages/kazam/frontend/preferences.py", line 92, in __init__
    self.restore_UI()
  File "/home/user/.local/lib/python3.10/site-packages/kazam/frontend/preferences.py", line 216, in restore_UI
    self.filechooser_picture.set_current_folder(prefs.autosave_picture_dir)
TypeError: Argument 1 does not allow None as a value

```

**Comment by henrywoo** [comment]
This should have been resolved by the latest version. Please update with `pip install -U kazam`.
